export const LIEN_TYPES = [
  { value: 'Abstract of Judgment', label: 'Abstract of Judgment' },
  { value: 'Abstract of Judgment Amendment', label: 'Abstract of Judgment Amendment' },
  { value: 'Abstract of Judgment Partial Release', label: 'Abstract of Judgment Partial Release' },
  { value: 'Abstract of Judgment Release', label: 'Abstract of Judgment Release' },
  { value: 'Affidavit', label: 'Affidavit' },
  { value: 'Affidavit Concerning A Deed', label: 'Affidavit Concerning A Deed' },
  { value: 'Affidavit For Mechanics Lien', label: 'Affidavit For Mechanics Lien' },
  { value: 'Affidavit of Death', label: 'Affidavit of Death' },
  { value: 'Affidavit of Death of Trustee', label: 'Affidavit of Death of Trustee' },
  { value: 'Affidavit of Estoppel', label: 'Affidavit of Estoppel' },
  { value: 'Affidavit of Heirship', label: 'Affidavit of Heirship' },
  { value: 'Affidavit of Lien', label: 'Affidavit of Lien' },
  { value: 'Affidavit of Purchase', label: 'Affidavit of Purchase' },
  { value: 'Affidavit of Release of Liens', label: 'Affidavit of Release of Liens' },
  { value: 'Affidavit of Termination of Joint Tenancy', label: 'Affidavit of Termination of Joint Tenancy' },
  { value: 'Agreement', label: 'Agreement' },
  { value: 'Agreement For Deed', label: 'Agreement For Deed' },
  { value: 'Agreement of Sale', label: 'Agreement of Sale' },
  { value: 'Amended Order & Final Judgment', label: 'Amended Order & Final Judgment' },
  { value: 'Amended Payment of Contractual Assessment Required', label: 'Amended Payment of Contractual Assessment Required' },
  { value: 'Amended Support Judgment', label: 'Amended Support Judgment' },
  { value: 'Amendment To Lien Agreement', label: 'Amendment To Lien Agreement' },
  { value: 'Assessment Energy Lien', label: 'Assessment Energy Lien' },
  { value: 'Assessment Energy Lien Amendment', label: 'Assessment Energy Lien Amendment' },
  { value: 'Assessment Energy Lien Release', label: 'Assessment Energy Lien Release' },
  { value: 'Assessment Lien', label: 'Assessment Lien' },
  { value: 'Assessment Lien Partial Release', label: 'Assessment Lien Partial Release' },
  { value: 'Assessment Lien Release', label: 'Assessment Lien Release' },
  { value: 'Assignment of Agreement of Sale', label: 'Assignment of Agreement of Sale' },
  { value: 'Assignment of Lease', label: 'Assignment of Lease' },
  { value: 'Assignment of Rents', label: 'Assignment of Rents' },
  { value: 'Assignment of Rents Assignment', label: 'Assignment of Rents Assignment' },
  { value: 'Assignment of Rents Partial Release', label: 'Assignment of Rents Partial Release' },
  { value: 'Assignment of Rents Release', label: 'Assignment of Rents Release' },
  { value: 'Assignment of Sale', label: 'Assignment of Sale' },
  { value: 'Assumption Agreement', label: 'Assumption Agreement' },
  { value: 'Assumption of Lease', label: 'Assumption of Lease' },
  { value: 'Bill of Sale', label: 'Bill of Sale' },
  { value: 'Bill of Sale Assignment', label: 'Bill of Sale Assignment' },
  { value: 'Cancellation of Sale', label: 'Cancellation of Sale' },
  { value: 'Certificate of Acknowledgment', label: 'Certificate of Acknowledgment' },
  { value: 'Certificate of Non-Compliance', label: 'Certificate of Non-Compliance' },
  { value: 'Certificate of Purchase', label: 'Certificate of Purchase' },
  { value: 'Certificate of Sale', label: 'Certificate of Sale' },
  { value: 'Certificate of Title', label: 'Certificate of Title' },
  { value: 'City Lien', label: 'City Lien' },
  { value: 'Code Enforcement Board Release of Lien', label: 'Code Enforcement Board Release of Lien' },
  { value: 'Code Enforcement Lien', label: 'Code Enforcement Lien' },
  { value: 'Community Facilities District Lien', label: 'Community Facilities District Lien' },
  { value: 'Community Property Agreement', label: 'Community Property Agreement' },
  { value: 'Contract', label: 'Contract' },
  { value: 'Contract Amendment', label: 'Contract Amendment' },
  { value: 'Contract Assignment', label: 'Contract Assignment' },
  { value: 'Contract For Deed', label: 'Contract For Deed' },
  { value: 'Contract For Deed Release', label: 'Contract For Deed Release' },
  { value: 'Contract of Sale', label: 'Contract of Sale' },
  { value: 'County Lien', label: 'County Lien' },
  { value: 'Decree of Divorce', label: 'Decree of Divorce' },
  { value: 'Department of Justice Lien', label: 'Department of Justice Lien' },
  { value: 'Divorce Judgment', label: 'Divorce Judgment' },
  { value: 'Energy Agreement Release', label: 'Energy Agreement Release' },
  { value: 'Energy Contract', label: 'Energy Contract' },
  { value: 'Execution', label: 'Execution' },
  { value: 'Federal Lien Subordination', label: 'Federal Lien Subordination' },
  { value: 'Federal Tax Lien', label: 'Federal Tax Lien' },
  { value: 'Federal Tax Lien Modification', label: 'Federal Tax Lien Modification' },
  { value: 'Federal Tax Lien Refiling', label: 'Federal Tax Lien Refiling' },
  { value: 'Federal Tax Lien Release', label: 'Federal Tax Lien Release' },
  { value: 'Financing Statement', label: 'Financing Statement' },
  { value: 'Financing Statement Amendment', label: 'Financing Statement Amendment' },
  { value: 'Financing Statement Assignment', label: 'Financing Statement Assignment' },
  { value: 'Financing Statement Continuation', label: 'Financing Statement Continuation' },
  { value: 'Financing Statement Modification', label: 'Financing Statement Modification' },
  { value: 'Financing Statement Partial Release', label: 'Financing Statement Partial Release' },
  { value: 'Financing Statement Release', label: 'Financing Statement Release' },
  { value: 'Financing Statement Subordination', label: 'Financing Statement Subordination' },
  { value: 'Financing Statement Termination', label: 'Financing Statement Termination' },
  { value: 'Judgment', label: 'Judgment' },
  { value: 'Judgment Amendment', label: 'Judgment Amendment' },
  { value: 'Judgment Assignment', label: 'Judgment Assignment' },
  { value: 'Judgment Distribution', label: 'Judgment Distribution' },
  { value: 'Judgment Lien', label: 'Judgment Lien' },
  { value: 'Judgment Lien Release', label: 'Judgment Lien Release' },
  { value: 'Judgment Partial Release', label: 'Judgment Partial Release' },
  { value: 'Judgment Release', label: 'Judgment Release' },
  { value: 'Lease', label: 'Lease' },
  { value: 'Lease Amendment', label: 'Lease Amendment' },
  { value: 'Lease Modification', label: 'Lease Modification' },
  { value: 'Levy', label: 'Levy' },
  { value: 'Levy Release', label: 'Levy Release' },
  { value: 'Lien', label: 'Lien' },
  { value: 'Lien Agreement', label: 'Lien Agreement' },
  { value: 'Lien Amendment', label: 'Lien Amendment' },
  { value: 'Lien Assignment', label: 'Lien Assignment' },
  { value: 'Lien Partial Release', label: 'Lien Partial Release' },
  { value: 'Lien Release', label: 'Lien Release' },
  { value: 'Lien Subordination', label: 'Lien Subordination' },
  { value: 'Lis Pendens', label: 'Lis Pendens' },
  { value: 'Lis Pendens Amendment', label: 'Lis Pendens Amendment' },
  { value: 'Lis Pendens Assignment', label: 'Lis Pendens Assignment' },
  { value: 'Lis Pendens Partial Release', label: 'Lis Pendens Partial Release' },
  { value: 'Lis Pendens Release', label: 'Lis Pendens Release' },
  { value: 'Lis Pendens - Mechanics Lien', label: 'Lis Pendens - Mechanics Lien' },
  { value: 'Loan Modification Agreement', label: 'Loan Modification Agreement' },
  { value: 'Mechanics Lien', label: 'Mechanics Lien' },
  { value: 'Mechanics Lien Amendment', label: 'Mechanics Lien Amendment' },
  { value: 'Mechanics Lien Extension', label: 'Mechanics Lien Extension' },
  { value: 'Mechanics Lien Partial Release', label: 'Mechanics Lien Partial Release' },
  { value: 'Mechanics Lien Release', label: 'Mechanics Lien Release' },
  { value: 'Modification (Unspecified)', label: 'Modification (Unspecified)' },
  { value: 'Negative Pledge Agreement', label: 'Negative Pledge Agreement' },
  { value: 'Note Release', label: 'Note Release' },
  { value: 'Notice of Redemption', label: 'Notice of Redemption' },
  { value: 'Notice of Sale', label: 'Notice of Sale' },
  { value: 'Order', label: 'Order' },
  { value: 'Order Amendment', label: 'Order Amendment' },
  { value: 'Order And Judgment', label: 'Order And Judgment' },
  { value: 'Order of Distribution', label: 'Order of Distribution' },
  { value: 'Order of Sale', label: 'Order of Sale' },
  { value: 'Order of Sale Amended', label: 'Order of Sale Amended' },
  { value: 'Order To Quiet Title', label: 'Order To Quiet Title' },
  { value: 'Partial Release of City Lien', label: 'Partial Release of City Lien' },
  { value: 'Partial Release of Department of Justice Lien', label: 'Partial Release of Department of Justice Lien' },
  { value: 'Partial Release of Economic Lien', label: 'Partial Release of Economic Lien' },
  { value: 'Partial Release of Support Judgment', label: 'Partial Release of Support Judgment' },
  { value: 'Payment of Contractual Assessment Required', label: 'Payment of Contractual Assessment Required' },
  { value: 'Postponed Property Tax Lien', label: 'Postponed Property Tax Lien' },
  { value: 'Probate Affidavit', label: 'Probate Affidavit' },
  { value: 'Probate Distribution', label: 'Probate Distribution' },
  { value: 'Probate Guardianship', label: 'Probate Guardianship' },
  { value: 'Probate Order', label: 'Probate Order' },
  { value: 'Probate Sale', label: 'Probate Sale' },
  { value: 'Purchase Agreement', label: 'Purchase Agreement' },
  { value: 'Quiet Title Judgment', label: 'Quiet Title Judgment' },
  { value: 'Quiet Title Notice of Lis Pendens', label: 'Quiet Title Notice of Lis Pendens' },
  { value: 'Release of City Lien', label: 'Release of City Lien' },
  { value: 'Release of County Lien', label: 'Release of County Lien' },
  { value: 'Release of Lien Agreement', label: 'Release of Lien Agreement' },
  { value: 'Release of Payment of Contractual Assessment Required', label: 'Release of Payment of Contractual Assessment Required' },
  { value: 'Release of Security Agreement', label: 'Release of Security Agreement' },
  { value: 'Request For Notice of Sale -Hoa Lien', label: 'Request For Notice of Sale -Hoa Lien' },
  { value: 'Settlement Agreement', label: 'Settlement Agreement' },
  { value: 'Sewer Lien', label: 'Sewer Lien' },
  { value: 'State Tax Lien', label: 'State Tax Lien' },
  { value: 'State Tax Lien Extention', label: 'State Tax Lien Extention' },
  { value: 'State Tax Lien Partial Release', label: 'State Tax Lien Partial Release' },
  { value: 'State Tax Lien Release', label: 'State Tax Lien Release' },
  { value: 'Substitution of Trustee', label: 'Substitution of Trustee' },
  { value: 'Support Judgment', label: 'Support Judgment' },
  { value: 'Support Lien', label: 'Support Lien' },
  { value: 'Support Lien Release', label: 'Support Lien Release' },
  { value: 'Support Release', label: 'Support Release' },
  { value: 'Termination of Purchase Agreement', label: 'Termination of Purchase Agreement' },
  { value: 'Termination of Solar Energy Contract', label: 'Termination of Solar Energy Contract' },
  { value: 'Transfer On Death Affidavit', label: 'Transfer On Death Affidavit' },
  { value: 'Utility Lien', label: 'Utility Lien' }
];
