export const PROPERTY_TYPE_CATEGORY = [
  { value: 'Agricultural', label: 'Agricultural' },
  { value: 'Commercial', label: 'Commercial' },
  { value: 'Exempt', label: 'Exempt' },
  { value: 'Industrial', label: 'Industrial' },
  { value: 'Miscellaneous', label: 'Miscellaneous' },
  { value: 'Office', label: 'Office' },
  { value: 'Recreational', label: 'Recreational' },
  { value: 'Residential', label: 'Residential' },
  { value: 'Vacant Land', label: 'Vacant Land' }
];

export const PROPERTY_TYPE_DETAIL = [
  // Agricultural (27 items)
  { value: 'Agricultural/Rural', label: 'Agricultural/Rural' },
  { value: 'Cannibis Grow Facility', label: 'Cannibis Grow Facility' },
  { value: 'Crop Land, Fields or Row Crops', label: 'Crop Land, Fields or Row Crops' },
  { value: 'Crops (Harvested)', label: 'Crops (Harvested)' },
  { value: 'Crops (In Ground)', label: 'Crops (In Ground)' },
  { value: 'Dairy Farm', label: 'Dairy Farm' },
  { value: 'Desert or Barren Land', label: 'Desert or Barren Land' },
  { value: 'Farm', label: 'Farm' },
  { value: 'Feedlots', label: 'Feedlots' },
  { value: 'Grove', label: 'Grove' },
  { value: 'Horticulture or Growing Houses', label: 'Horticulture or Growing Houses' },
  { value: 'Irrigation or Flood Control', label: 'Irrigation or Flood Control' },
  { value: 'Livestock Parcel', label: 'Livestock Parcel' },
  { value: 'Miscellaneous Structures', label: 'Miscellaneous Structures' },
  { value: 'Natural Resources', label: 'Natural Resources' },
  { value: 'Orchard', label: 'Orchard' },
  { value: 'Pasture or Meadow', label: 'Pasture or Meadow' },
  { value: 'Poultry Farm', label: 'Poultry Farm' },
  { value: 'Ranch', label: 'Ranch' },
  { value: 'Range Land', label: 'Range Land' },
  { value: 'Resevoir or Water Supply', label: 'Resevoir or Water Supply' },
  { value: 'Rural Improved (Non-Residential)', label: 'Rural Improved (Non-Residential)' },
  { value: 'Timberland or Forest', label: 'Timberland or Forest' },
  { value: 'Truck Crops', label: 'Truck Crops' },
  { value: 'Vineyard', label: 'Vineyard' },
  { value: 'Well Site', label: 'Well Site' },
  { value: 'Wildlife Refuge', label: 'Wildlife Refuge' },

  // Commercial (64 items)
  { value: 'Appliance Store', label: 'Appliance Store' },
  { value: 'Auto Repair or Garage', label: 'Auto Repair or Garage' },
  { value: 'Automated Car Wash', label: 'Automated Car Wash' },
  { value: 'Bakery', label: 'Bakery' },
  { value: 'Bar or Tavern', label: 'Bar or Tavern' },
  { value: 'Barber or Hair Salon', label: 'Barber or Hair Salon' },
  { value: 'Bed & Breakfast', label: 'Bed & Breakfast' },
  { value: 'Cannibis Dispensary', label: 'Cannibis Dispensary' },
  { value: 'Car Wash', label: 'Car Wash' },
  { value: 'Casino', label: 'Casino' },
  { value: 'Commercial Building, Mail Order Showroom or Commercial Warehouse', label: 'Commercial Building, Mail Order Showroom or Commercial Warehouse' },
  { value: 'Commercial Condominium (Not Offices)', label: 'Commercial Condominium (Not Offices)' },
  { value: 'Commercial/Office/Residential (Mixed Use)', label: 'Commercial/Office/Residential (Mixed Use)' },
  { value: 'Community Shopping Center, Plaza or Mini-Mall', label: 'Community Shopping Center, Plaza or Mini-Mall' },
  { value: 'Convenience Store', label: 'Convenience Store' },
  { value: 'Convenience Store with Fuel Pump', label: 'Convenience Store with Fuel Pump' },
  { value: 'Day Care or Preschool Facility', label: 'Day Care or Preschool Facility' },
  { value: 'Department Store', label: 'Department Store' },
  { value: 'Department Store (Multi-Story)', label: 'Department Store (Multi-Story)' },
  { value: 'Drug Store or Pharmacy', label: 'Drug Store or Pharmacy' },
  { value: 'Dry Cleaner or Laundry Service', label: 'Dry Cleaner or Laundry Service' },
  { value: 'Farm Supply and Equipment (Retail)', label: 'Farm Supply and Equipment (Retail)' },
  { value: 'Fast Food Restaurant or Drive-Through', label: 'Fast Food Restaurant or Drive-Through' },
  { value: 'Florist, Nursery or Greenhouse', label: 'Florist, Nursery or Greenhouse' },
  { value: 'Funeral Home or Mortuary', label: 'Funeral Home or Mortuary' },
  { value: 'Gas Station', label: 'Gas Station' },
  { value: 'General', label: 'General' },
  { value: 'Grocery or Supermarket', label: 'Grocery or Supermarket' },
  { value: 'Home Improvement Center', label: 'Home Improvement Center' },
  { value: 'Hotel', label: 'Hotel' },
  { value: 'Hotel Resort', label: 'Hotel Resort' },
  { value: 'Hotel/Motel', label: 'Hotel/Motel' },
  { value: 'Kennel', label: 'Kennel' },
  { value: 'Laundromat', label: 'Laundromat' },
  { value: 'Liquor Store', label: 'Liquor Store' },
  { value: 'Mini-Warehouse or Self-Storage', label: 'Mini-Warehouse or Self-Storage' },
  { value: 'Miscellaneous Commercial', label: 'Miscellaneous Commercial' },
  { value: 'Miscellaneous Commerical Multi-Parcel', label: 'Miscellaneous Commerical Multi-Parcel' },
  { value: 'Motel', label: 'Motel' },
  { value: 'Neighborhood Shopping Center, Strip Mall or Enterprise Zone', label: 'Neighborhood Shopping Center, Strip Mall or Enterprise Zone' },
  { value: 'Nightclub or Cocktail Lounge', label: 'Nightclub or Cocktail Lounge' },
  { value: 'Parking Garage or Structure', label: 'Parking Garage or Structure' },
  { value: 'Parking Lot', label: 'Parking Lot' },
  { value: 'Pet Boarding and Grooming', label: 'Pet Boarding and Grooming' },
  { value: 'Regional Shopping Center or Mall', label: 'Regional Shopping Center or Mall' },
  { value: 'Restaurant', label: 'Restaurant' },
  { value: 'Retail Printer or Delivery Service (e.g. UPS, Fedex)', label: 'Retail Printer or Delivery Service (e.g. UPS, Fedex)' },
  { value: 'Retail Stores', label: 'Retail Stores' },
  { value: 'Retail/Residential (Mixed Use)', label: 'Retail/Residential (Mixed Use)' },
  { value: 'Roadside Market', label: 'Roadside Market' },
  { value: 'Self-Serve Car Wash', label: 'Self-Serve Car Wash' },
  { value: 'Service Shop', label: 'Service Shop' },
  { value: 'Service Station', label: 'Service Station' },
  { value: 'Service Station with Food Mart', label: 'Service Station with Food Mart' },
  { value: 'Shopping Center Common Area', label: 'Shopping Center Common Area' },
  { value: 'Store (Multi-Story)', label: 'Store (Multi-Story)' },
  { value: 'Store or Retail Outlet', label: 'Store or Retail Outlet' },
  { value: 'Store/Office', label: 'Store/Office' },
  { value: 'Take-Out Restaurant', label: 'Take-Out Restaurant' },
  { value: 'Truck Stop', label: 'Truck Stop' },
  { value: 'Vacant Land', label: 'Vacant Land' },
  { value: 'Vehicle Rental and Sales', label: 'Vehicle Rental and Sales' },
  { value: 'Veterinary Clinic or Animal Hospital', label: 'Veterinary Clinic or Animal Hospital' },
  { value: 'Wholesale Outlet or Discount Store', label: 'Wholesale Outlet or Discount Store' },

  // Exempt (44 items)
  { value: 'Cemetery', label: 'Cemetery' },
  { value: 'Charitable or Fraternal Organization', label: 'Charitable or Fraternal Organization' },
  { value: 'City, Municipal, Town or Village Owned', label: 'City, Municipal, Town or Village Owned' },
  { value: 'College, University or Vocational School', label: 'College, University or Vocational School' },
  { value: 'Community Center', label: 'Community Center' },
  { value: 'Correctional Facility, Jail, Prison or Insane Asylum', label: 'Correctional Facility, Jail, Prison or Insane Asylum' },
  { value: 'County Owned', label: 'County Owned' },
  { value: 'Crematorium or Mortuary', label: 'Crematorium or Mortuary' },
  { value: 'Cultural or Historical', label: 'Cultural or Historical' },
  { value: 'Emergency', label: 'Emergency' },
  { value: 'Exempt Full or Partial', label: 'Exempt Full or Partial' },
  { value: 'Federal Property', label: 'Federal Property' },
  { value: 'Forest', label: 'Forest' },
  { value: 'Full or Partial', label: 'Full or Partial' },
  { value: 'Government Administrative Office', label: 'Government Administrative Office' },
  { value: 'Governmental or Public Use', label: 'Governmental or Public Use' },
  { value: 'Historical District', label: 'Historical District' },
  { value: 'Historical Office', label: 'Historical Office' },
  { value: 'Historical Park or Site', label: 'Historical Park or Site' },
  { value: 'Historical Recreation or Entertainment', label: 'Historical Recreation or Entertainment' },
  { value: 'Historical Residence', label: 'Historical Residence' },
  { value: 'Historical Retail', label: 'Historical Retail' },
  { value: 'Historical Transient Lodging', label: 'Historical Transient Lodging' },
  { value: 'Historical Warehouse', label: 'Historical Warehouse' },
  { value: 'Institutional (General)', label: 'Institutional (General)' },
  { value: 'Medical Clinic', label: 'Medical Clinic' },
  { value: 'Military', label: 'Military' },
  { value: 'Native American Lands', label: 'Native American Lands' },
  { value: 'Other Exempt Property', label: 'Other Exempt Property' },
  { value: 'Parochial or Private School', label: 'Parochial or Private School' },
  { value: 'Post Office', label: 'Post Office' },
  { value: 'Private Historical', label: 'Private Historical' },
  { value: 'Private Hospital', label: 'Private Hospital' },
  { value: 'Private Utility', label: 'Private Utility' },
  { value: 'Public College or University', label: 'Public College or University' },
  { value: 'Public Health Care Facility', label: 'Public Health Care Facility' },
  { value: 'Public Hospital', label: 'Public Hospital' },
  { value: 'Public School', label: 'Public School' },
  { value: 'Public Utility', label: 'Public Utility' },
  { value: 'Recreational Non-Taxable (Camps, Boy/Girl Scouts)', label: 'Recreational Non-Taxable (Camps, Boy/Girl Scouts)' },
  { value: 'Religious, Church, Worship', label: 'Religious, Church, Worship' },
  { value: 'Retirement, Nursing or Convalescent Home', label: 'Retirement, Nursing or Convalescent Home' },
  { value: 'State Owned', label: 'State Owned' },
  { value: 'Welfare, Social Service or Low Income Housing', label: 'Welfare, Social Service or Low Income Housing' },

  // Industrial (64 items)
  { value: 'Airport', label: 'Airport' },
  { value: 'Bulk Storage Tanks', label: 'Bulk Storage Tanks' },
  { value: 'Bus Terminal', label: 'Bus Terminal' },
  { value: 'Cable TV Station', label: 'Cable TV Station' },
  { value: 'Cannery', label: 'Cannery' },
  { value: 'Cellular', label: 'Cellular' },
  { value: 'Chemical Plant', label: 'Chemical Plant' },
  { value: 'Cold Storage', label: 'Cold Storage' },
  { value: 'Commercial Auto Transportation', label: 'Commercial Auto Transportation' },
  { value: 'Common Area (Industrial)', label: 'Common Area (Industrial)' },
  { value: 'Communications', label: 'Communications' },
  { value: 'Condominiums (Industrial)', label: 'Condominiums (Industrial)' },
  { value: 'Construction or Contracting Services', label: 'Construction or Contracting Services' },
  { value: 'Distillery, Brewing or Bottling Facility', label: 'Distillery, Brewing or Bottling Facility' },
  { value: 'Distribution Warehouse', label: 'Distribution Warehouse' },
  { value: 'Dump Site', label: 'Dump Site' },
  { value: 'Factory', label: 'Factory' },
  { value: 'Food Packing Plant', label: 'Food Packing Plant' },
  { value: 'Food Processing Facility', label: 'Food Processing Facility' },
  { value: 'Foundry or Industrial Plant', label: 'Foundry or Industrial Plant' },
  { value: 'Freeway or State Highway', label: 'Freeway or State Highway' },
  { value: 'General', label: 'General' },
  { value: 'Grain Elevator', label: 'Grain Elevator' },
  { value: 'Harbor & Marine Transportation', label: 'Harbor & Marine Transportation' },
  { value: 'Heavy Industrial', label: 'Heavy Industrial' },
  { value: 'Heavy Manufacturing', label: 'Heavy Manufacturing' },
  { value: 'Industrial Loft Building', label: 'Industrial Loft Building' },
  { value: 'Industrial Park', label: 'Industrial Park' },
  { value: 'Labor Camp', label: 'Labor Camp' },
  { value: 'Light Assembly Facility', label: 'Light Assembly Facility' },
  { value: 'Light Industrial', label: 'Light Industrial' },
  { value: 'Light Manufacturing', label: 'Light Manufacturing' },
  { value: 'Lumber & Wood Product Manufacturing', label: 'Lumber & Wood Product Manufacturing' },
  { value: 'Lumber or Building Materials Yard', label: 'Lumber or Building Materials Yard' },
  { value: 'Marine or Boat Repair Facility', label: 'Marine or Boat Repair Facility' },
  { value: 'Microwave', label: 'Microwave' },
  { value: 'Mill', label: 'Mill' },
  { value: 'Mining Facility', label: 'Mining Facility' },
  { value: 'Miscellaneous Industrial', label: 'Miscellaneous Industrial' },
  { value: 'Multi-Tenant Industrial Building', label: 'Multi-Tenant Industrial Building' },
  { value: 'Paper Product Manufacturing', label: 'Paper Product Manufacturing' },
  { value: 'Pollution Control', label: 'Pollution Control' },
  { value: 'Printing and Publishing (Light Industrial)', label: 'Printing and Publishing (Light Industrial)' },
  { value: 'Processing Plant', label: 'Processing Plant' },
  { value: 'Quarry', label: 'Quarry' },
  { value: 'R&D, Laboratory or Research Facility', label: 'R&D, Laboratory or Research Facility' },
  { value: 'Radio or TV Station', label: 'Radio or TV Station' },
  { value: 'Railroad', label: 'Railroad' },
  { value: 'Recycling', label: 'Recycling' },
  { value: 'Refinery', label: 'Refinery' },
  { value: 'Road, Street or Bridge', label: 'Road, Street or Bridge' },
  { value: 'Shipyard or Boat Storage', label: 'Shipyard or Boat Storage' },
  { value: 'Slaughterhouse or Stockyard', label: 'Slaughterhouse or Stockyard' },
  { value: 'Storage Yard (junk, auto wrecking, salvage)', label: 'Storage Yard (junk, auto wrecking, salvage)' },
  { value: 'Storage Yard (open storage, light equipment, material)', label: 'Storage Yard (open storage, light equipment, material)' },
  { value: 'Sugar Refinery', label: 'Sugar Refinery' },
  { value: 'Telephone or Telegraph Facility', label: 'Telephone or Telegraph Facility' },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Transportation & Communications', label: 'Transportation & Communications' },
  { value: 'Truck Terminal', label: 'Truck Terminal' },
  { value: 'Vacant Land', label: 'Vacant Land' },
  { value: 'Warehouse (Industrial)', label: 'Warehouse (Industrial)' },
  { value: 'Waste Disposal or Sewage Plant', label: 'Waste Disposal or Sewage Plant' },
  { value: 'Winery', label: 'Winery' },

  // Miscellaneous (39 items)
  { value: 'Aircraft', label: 'Aircraft' },
  { value: 'Business Personal Property', label: 'Business Personal Property' },
  { value: 'Common Area', label: 'Common Area' },
  { value: 'Easement', label: 'Easement' },
  { value: 'Equipment or Supplies', label: 'Equipment or Supplies' },
  { value: 'General', label: 'General' },
  { value: 'Goods in Transit', label: 'Goods in Transit' },
  { value: 'Homestead', label: 'Homestead' },
  { value: 'Intangible Personal Property', label: 'Intangible Personal Property' },
  { value: 'Inventory', label: 'Inventory' },
  { value: 'Leasehold Rights', label: 'Leasehold Rights' },
  { value: 'Livestock', label: 'Livestock' },
  { value: 'Miscellaneous Business Personal Property', label: 'Miscellaneous Business Personal Property' },
  { value: 'Miscellaneous Personal Property', label: 'Miscellaneous Personal Property' },
  { value: 'Miscellaneous Structures', label: 'Miscellaneous Structures' },
  { value: 'Miscellaneous Vehicles', label: 'Miscellaneous Vehicles' },
  { value: 'Motor Vehicles', label: 'Motor Vehicles' },
  { value: 'Parcel with Improvements', label: 'Parcel with Improvements' },
  { value: 'Personal Property', label: 'Personal Property' },
  { value: 'Petroleum & Gas Wells', label: 'Petroleum & Gas Wells' },
  { value: 'Pipeline or Right-of-Way', label: 'Pipeline or Right-of-Way' },
  { value: 'Possessory Interest', label: 'Possessory Interest' },
  { value: 'Rail Right-of-Way and Track', label: 'Rail Right-of-Way and Track' },
  { value: 'Railroad Rolling Stock', label: 'Railroad Rolling Stock' },
  { value: 'Recreational Vehicles or Travel Trailers', label: 'Recreational Vehicles or Travel Trailers' },
  { value: 'Right-of-Way', label: 'Right-of-Way' },
  { value: 'Road Right-of-Way', label: 'Road Right-of-Way' },
  { value: 'Royalty Interest', label: 'Royalty Interest' },
  { value: 'Spacecraft', label: 'Spacecraft' },
  { value: 'Structures', label: 'Structures' },
  { value: 'Structures on Leased Land', label: 'Structures on Leased Land' },
  { value: 'Sub-Surface Rights', label: 'Sub-Surface Rights' },
  { value: 'Surface Rights', label: 'Surface Rights' },
  { value: 'Temporary Structures', label: 'Temporary Structures' },
  { value: 'Unknown', label: 'Unknown' },
  { value: 'Utilities', label: 'Utilities' },
  { value: 'Water Rights', label: 'Water Rights' },
  { value: 'Watercraft', label: 'Watercraft' },
  { value: 'Working Interest', label: 'Working Interest' },

  // Office (13 items)
  { value: 'Commercial Office', label: 'Commercial Office' },
  { value: 'Commerical/Industrial (Mixed Use)', label: 'Commerical/Industrial (Mixed Use)' },
  { value: 'Common Area (Not Shopping Center)', label: 'Common Area (Not Shopping Center)' },
  { value: 'Condominium Offices', label: 'Condominium Offices' },
  { value: 'Dental Building', label: 'Dental Building' },
  { value: 'Financial Building or Bank', label: 'Financial Building or Bank' },
  { value: 'Medical Building or Clinic', label: 'Medical Building or Clinic' },
  { value: 'Mobile Commercial Units', label: 'Mobile Commercial Units' },
  { value: 'Office Building (General)', label: 'Office Building (General)' },
  { value: 'Office Building (Multi-Story)', label: 'Office Building (Multi-Story)' },
  { value: 'Professional Building', label: 'Professional Building' },
  { value: 'Professional Building (Multi-Story)', label: 'Professional Building (Multi-Story)' },
  { value: 'Skyscraper or Highrise (Commercial Offices)', label: 'Skyscraper or Highrise (Commercial Offices)' },

  // Recreational (33 items)
  { value: 'Amusement Park or Tourist Attraction', label: 'Amusement Park or Tourist Attraction' },
  { value: 'Arcade (Amusement)', label: 'Arcade (Amusement)' },
  { value: 'Arena or Convention Center', label: 'Arena or Convention Center' },
  { value: 'Auditorium', label: 'Auditorium' },
  { value: 'Boat Slips, Marina or Yacht Club', label: 'Boat Slips, Marina or Yacht Club' },
  { value: 'Bowling Alley', label: 'Bowling Alley' },
  { value: 'Campground or RV Park', label: 'Campground or RV Park' },
  { value: 'Club, Lodge or Professional Association', label: 'Club, Lodge or Professional Association' },
  { value: 'Country Club', label: 'Country Club' },
  { value: 'Dance Hall', label: 'Dance Hall' },
  { value: 'Drive-In Theater', label: 'Drive-In Theater' },
  { value: 'Driving Range', label: 'Driving Range' },
  { value: 'Fairgrounds', label: 'Fairgrounds' },
  { value: 'Fish Camp, Game Club or Target Range', label: 'Fish Camp, Game Club or Target Range' },
  { value: 'Go-Cart Track, Miniature Golf or Water Slide', label: 'Go-Cart Track, Miniature Golf or Water Slide' },
  { value: 'Golf Course', label: 'Golf Course' },
  { value: 'Gym or Health Spa', label: 'Gym or Health Spa' },
  { value: 'Museum, Library or Art Gallery', label: 'Museum, Library or Art Gallery' },
  { value: 'Outdoor Recreation (Beach, Mountain or Desert)', label: 'Outdoor Recreation (Beach, Mountain or Desert)' },
  { value: 'Park, Playground or Picnic Area', label: 'Park, Playground or Picnic Area' },
  { value: 'Pier or Wharf (Recreation)', label: 'Pier or Wharf (Recreation)' },
  { value: 'Pool Hall or Billiar Parlor', label: 'Pool Hall or Billiar Parlor' },
  { value: 'Public Swimming Pool', label: 'Public Swimming Pool' },
  { value: 'Race Track', label: 'Race Track' },
  { value: 'Racquet or Tennis Court', label: 'Racquet or Tennis Court' },
  { value: 'Recreation Center', label: 'Recreation Center' },
  { value: 'Recreational/Entertainment', label: 'Recreational/Entertainment' },
  { value: 'Riding Stable or Trails', label: 'Riding Stable or Trails' },
  { value: 'Skating Rink or Roller Skating Facility', label: 'Skating Rink or Roller Skating Facility' },
  { value: 'Sports Complex', label: 'Sports Complex' },
  { value: 'Stadium', label: 'Stadium' },
  { value: 'Theater', label: 'Theater' },
  { value: 'Zoo', label: 'Zoo' },

  // Residential (45 items)
  { value: 'Accessory Dwelling Unit', label: 'Accessory Dwelling Unit' },
  { value: 'Apartment House (100+ Units)', label: 'Apartment House (100+ Units)' },
  { value: 'Apartment House (5+ Units)', label: 'Apartment House (5+ Units)' },
  { value: 'Apartments', label: 'Apartments' },
  { value: 'Barndominium', label: 'Barndominium' },
  { value: 'Boarding House or Rooming House', label: 'Boarding House or Rooming House' },
  { value: 'Bungalow', label: 'Bungalow' },
  { value: 'Cluster Home', label: 'Cluster Home' },
  { value: 'Condominium Building', label: 'Condominium Building' },
  { value: 'Condominium Unit', label: 'Condominium Unit' },
  { value: 'Cooperative Building', label: 'Cooperative Building' },
  { value: 'Cooperative Unit', label: 'Cooperative Unit' },
  { value: 'Dormitory', label: 'Dormitory' },
  { value: 'Duplex', label: 'Duplex' },
  { value: 'Fraternity or Sorority House', label: 'Fraternity or Sorority House' },
  { value: 'Garden Apartment, Court Apartment (5+ Units)', label: 'Garden Apartment, Court Apartment (5+ Units)' },
  { value: 'Garden Home', label: 'Garden Home' },
  { value: 'General', label: 'General' },
  { value: 'Highrise Apartment', label: 'Highrise Apartment' },
  { value: 'Landominium', label: 'Landominium' },
  { value: 'Miscellaneous Residential Improvement', label: 'Miscellaneous Residential Improvement' },
  { value: 'Miscellaneous Residential Improvement', label: 'Miscellaneous Residential Improvement' },
  { value: 'Mobile Home Park or Trailer Park', label: 'Mobile Home Park or Trailer Park' },
  { value: 'Mobile/Manufactured Home', label: 'Mobile/Manufactured Home' },
  { value: 'Module or Prefabricated Homes', label: 'Module or Prefabricated Homes' },
  { value: 'Multi-Family Dwelling', label: 'Multi-Family Dwelling' },
  { value: 'Patio Home', label: 'Patio Home' },
  { value: 'Planned Unit Development', label: 'Planned Unit Development' },
  { value: 'Quadruplex', label: 'Quadruplex' },
  { value: 'Residential Common Area', label: 'Residential Common Area' },
  { value: 'Residential Condominium Development', label: 'Residential Condominium Development' },
  { value: 'Residential Income (Multi-Family)', label: 'Residential Income (Multi-Family)' },
  { value: 'Residential Parking Garage', label: 'Residential Parking Garage' },
  { value: 'Residential Storage Space', label: 'Residential Storage Space' },
  { value: 'Row House', label: 'Row House' },
  { value: 'Rurual/Agricultural Residence', label: 'Rurual/Agricultural Residence' },
  { value: 'Seasonal, Cabin, Vacation Residence', label: 'Seasonal, Cabin, Vacation Residence' },
  { value: 'Single Family', label: 'Single Family' },
  { value: 'Single Family Residential (Assumed)', label: 'Single Family Residential (Assumed)' },
  { value: 'Timeshare', label: 'Timeshare' },
  { value: 'Tiny House', label: 'Tiny House' },
  { value: 'Townhouse', label: 'Townhouse' },
  { value: 'Triplex', label: 'Triplex' },
  { value: 'Vacant Land', label: 'Vacant Land' },
  { value: 'Zero Lot Line', label: 'Zero Lot Line' },

  // Vacant Land (21 items)
  { value: 'Abandoned or Contaminated Site', label: 'Abandoned or Contaminated Site' },
  { value: 'Centrally Assessed', label: 'Centrally Assessed' },
  { value: 'Destroyed or Uninhabitable Improvement', label: 'Destroyed or Uninhabitable Improvement' },
  { value: 'Exempt', label: 'Exempt' },
  { value: 'General', label: 'General' },
  { value: 'Government', label: 'Government' },
  { value: 'Institutional', label: 'Institutional' },
  { value: 'Multi-Family', label: 'Multi-Family' },
  { value: 'Private Preserve or Open Space', label: 'Private Preserve or Open Space' },
  { value: 'Recreational', label: 'Recreational' },
  { value: 'Redevelopment Agency or Zone', label: 'Redevelopment Agency or Zone' },
  { value: 'Regulating Districts & Assessments', label: 'Regulating Districts & Assessments' },
  { value: 'Rural/Agricultural', label: 'Rural/Agricultural' },
  { value: 'Special Purpose', label: 'Special Purpose' },
  { value: 'State Board of Equalization - Special Assessments', label: 'State Board of Equalization - Special Assessments' },
  { value: 'Under Construction', label: 'Under Construction' },
  { value: 'Unspecified Improvement', label: 'Unspecified Improvement' },
  { value: 'Unusable Land', label: 'Unusable Land' },
  { value: 'Vacant Land', label: 'Vacant Land' },
  { value: 'Waste Land, Marsh or Swamp', label: 'Waste Land, Marsh or Swamp' },
  { value: 'Water Area (Lakes; River; Shore)', label: 'Water Area (Lakes; River; Shore)' },
];
